---
- name: Create Network Interface
  azure_rm_networkinterface:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ item }}"
    virtual_network_name: "{{ item.azure_virtual_network_name }}"
    subnet_name: default
    public_ip: "{{ azure_public_ip }}"
  with_items: "{{ azure_vm_name }}"
