---
- block:
  - name: Check common required variables are defined
    fail: msg="Required variables for vm's not defined"
    when: (azure_client_id is undefined or azure_client_id is none or azure_client_id | trim == "") or
          (azure_secret is undefined or azure_secret is none or azure_secret | trim == "") or
          (azure_subscription_id is undefined or azure_subscription_id is none or azure_subscription_id | trim == "") or
          (azure_tenant is undefined or azure_tenant is none or azure_tenant | trim == "") or
          (azure_resource_group is undefined or azure_resource_group is none or azure_resource_group | trim == "") or
    with_items: all

  - name: Check role required variables are defined
    fail: msg="Required variables for vm's not defined"
    when: (item.azure_network_interface_name is undefined or item.azure_network_interface_name is none or item.azure_network_interface_name | trim == "") or
          (item.name is undefined or item.name is none or item.name | trim == "") or
    with_items: "{{ azure_vm_name }}"

  - name: Create Network Interface
    azure_rm_networkinterface:
      client_id: "{{ azure_client_id }}"
      secret: "{{ azure_secret }}"
      subscription_id: "{{ azure_subscription_id }}"
      tenant: "{{ azure_tenant }}"
      resource_group: "{{ azure_resource_group }}"
      name: "{{ item.azure_network_interface_name }}"
      virtual_network_name: "{{ azure_virtual_network_name }}"
      subnet_name: default
      public_ip: "{{ azure_public_ip }}"
    with_items: "{{ azure_vm_name }}"
