---
- name: Create Network Interface
  azure_rm_networkinterface:
    ad_user: b_mcintyre@hotmail.com
    password: compaq25
    #client_id: "{{ azure_client_id }}"
    #secret: "{{ azure_secret }}"
    #subscription_id: "{{ azure_subscription_id }}"
    #tenant: "{{ azure_tenant }}"
    #resource_group: "{{ item.azure_resource_group }}"
    resource_group: Mocatad_EV16_AS
    name: "{{ item.azure_network_interface_name }}"
    #virtual_network_name: "{{ item.azure_virtual_network_name }}"
    virtual_network_name: Mocatad_AS
    #security_group_name: "{{ item.azure_security_group_name }}"
    subnet_name: "{{ item.azure_subnet_name }}"
    subnet_name: Mocatad_AS_NP_Ext_WebApp
    public_ip: "{{ item.azure_public_ip }}"
    public_ip: false
    #public_ip_address_name: "{{ item.name }}"
    #private_ip_address: "{{ item.azure_private_ip_address }}"
    #private_ip_allocation_method: "{{ item.azure_private_ip_allocation_method }}"
  with_items: "{{ azure_name }}"
