---
- name: Create Network Interface
  azure_rm_networkinterface:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ item.azure_resource_group }}"
    name: "{{ item.azure_network_interface_name }}"
    virtual_network_name: "{{ item.azure_virtual_network_name }}"
    security_group_name: "{{ item.azure_security_group_name }}"
    subnet_name: "{{ item.azure_subnet_name }}"
    public_ip: "{{ item.azure_public_ip }}"
    public_ip_address_name: "{{ item.name }}"
    public_ip_allocation_method: "{{ item.azure_public_ip_allocation_method }}"
    private_ip: "{{ item.azure_private_ip_address }}"
    private_ip_allocation_method: "{{ item.azure_private_ip_allocation_method }}"
  with_items: "{{ azure_name }}"
