---
- name: Deploy ARM Template using Parameters
  azure_rm_deployment:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group_name: "{{ azure_resource_group }}"
    location: "{{ azure_location }}"
    template_link: "{{ azure_template_link }}"
    parameters:
      #newStorageAccountName:
        #value: "{{ azure_storage_account_name }}"
      adminUsername:
        value: "{{ azure_admin_username }}"
      adminPassword:
        value: "{{ azure_admin_password}}"
      dnsLabelPrefix:
        value: "{{ azure_vm_name }}"
      vmName:
        value: "{{ azure_vm_name }}"
      #vmSize:
        #value: "{{ azure_vm_size }}"
      windowsOSVersion:
        value: "{{ azure_windows_os_version }}"
      nicname:
        value: "{{ azure_network_interface_name }}"
      virtualNetworkName:
        value: "{{ azure_virtual_network_name }}"
      publicIPAddressName:
        value: "{{ azure_public_ip_name  }}"

    wait_for_deployment_completion: "{{ azure_wait_for_deployment_completion }}"
    wait_for_deployment_polling_period: "{{ azure_wait_for_deployment_polling_period }}"
    state: present
