---
- name: Create Security Group
  azure_rm_securitygroup:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ item.azure_resource_group }}"
    name: "{{ item.azure_security_group_name }}"
  with_items: "{{ azure_name }}"
