---
# tasks file for azure-prereqs

- name: Ensure required yum dependancy packages are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ prereq_yum_packages }}"
  register: result


- name: Ensure required Azure pip packages are installed
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ azure_pip_packages }}"
  register: result
