
---
- name: Delete VM
  azure_rm_virtualmachine:
    client_id: "{{ client_id }}"
    secret: "{{ secret }}"
    subscription_id: "{{ subscription_id }}"
    tenant: "{{ tenant }}"
    resource_group: "{{ resource_group }}"
    name: "{{ item }}"
    state: absent
    remove_on_absent:
      - network_interfaces
      - virtual_storage
      - public_ips
  with_items: "{{ vm_name }}"
