---
- name: Delete Storage Account
  azure_rm_storageaccount:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ item }}01"
    state: absent
  with_items: "{{ azure_vm_name }}"
