---
- name: Power Off
  azure_rm_virtualmachine:
    client_id: "{{ client_id }}"
    secret: "{{ secret }}"
    subscription_id: "{{ subscription_id }}"
    tenant: "{{ tenant }}"
    resource_group: "{{ resource_group }}"
    name: {{ item }}
    started: no
  with_items: {{ vm_name }}
  register: output

- debug: var=output
  when: playbook_debug

- assert:
    that: "azure_vm.powerstate not in ['starting', 'running']"
