---
- name: Create Storage Account
  azure_rm_storageaccount:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ item.azure_resource_group }}"
    name: "{{ item.azure_storage_account_name }}"
    account_type: "{{ item.azure_storage_account_type }}"
    kind: "{{ item.azure_storage_account_kind }}"
    state: present
  with_items: "{{ azure_name }}"
