---
- name: Delete Network Interface
  azure_rm_security_group:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ item.azure_network_interface_name }}"
    state: absent
  with_items: "{{ azure_vm_name }}"
