---
- name: Restart VM
  azure_rm_virtualmachine:
    client_id: "{{ client_id }}"
    secret: "{{ secret }}"
    subscription_id: "{{ subscription_id }}"
    tenant: "{{ tenant }}"
    resource_group: "{{ resource_group }}"
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password}}"
    name: "{{ item }}"
    restarted: yes
    state: present
  with_items: "{{ vm_name }}"
  
