---
- name: Create VM
  azure_rm_virtualmachine:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ item.name }}"
    network_interface_names: "{{ item.azure_network_interface_name }}"
    storage_account_name: "{{ item.azure_storage_account_name }}"
    admin_username: "{{ azure_admin_username }}"
    admin_password: "{{ azure_admin_password}}"
    image:
      offer: "{{ azure_offer }}"
      publisher: "{{ azure_publisher }}"
      sku: "{{ azure_sku }}"
      version: "{{ azure_version }}"
    vm_size: "{{ azure_vm_size }}"
    os_type: "{{ azure_os_type }}"
  with_items: "{{ azure_vm_name }}"
