#- name: Create VM
  #azure_rm_virtualmachine:
    #client_id: "{{ client_id }}"
    #secret: "{{ secret }}"
    #subscription_id: "{{ subscription_id }}"
    #tenant: "{{ tenant }}"
    #resource_group: "{{ resource_group }}"
    #name: "{{ vm_name }}"
    #started: true
    #vm_size: "{{ vm_size }}"
    #admin_username: "{{ admin_username }}"
    #admin_password: "{{ admin_password }}"
    #os_type: "{{ os_type }}"
    #image:
      #publisher: "{{ publisher }}"
      #offer: "{{ offer }}"
      #sku: "{{ sku }}"
      #version: "{{ version }}"

- name: Create VM with defaults
  azure_rm_virtualmachine:
    client_id: "{{ client_id }}"
    secret: "{{ secret }}"
    subscription_id: "{{ subscription_id }}"
    tenant: "{{ tenant }}"
    resource_group: "{{ resource_group }}"
    name: testvm10
    public_ip_allocation_method:
      got: none
    admin_username: bradtest
    admin_password: Password01
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.1'
      version: latest
