---
- name: Delete VM
  azure_rm_virtualmachine:
    client_id: "{{ client_id }}"
    secret: "{{ secret }}"
    subscription_id: "{{ subscription_id }}"
    tenant: "{{ tenant }}"
    resource_group: "{{ resource_group }}"
    name: testvm1
    network_interface_names: testvm1-nic1
