- name: Start VM
  azure_rm_virtualmachine:
    client_id: "{{ client_id }}"
    secret: "{{ secret }}"
    subscription_id: "{{ subscription_id }}"
    tenant: "{{ tenant }}"
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
    #state: present
    started: true
