---
- name: Delete Public IP
  azure_rm_publicipaddress:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ azure_name }}"
