---


- name: Get facts
  azure_rm_virtualmachineimage_facts:
    location: "{{ azure_location }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
  register: result
