---


- name: Get facts
  azure_rm_virtualmachineimage_facts:
    location: AustraliaSoutheast
    subscription_id: 321a0e15-f849-4a60-bc00-31a7f21a45bb
    tenant: dbc218fd-b8f5-4a62-9f50-b698b859feec
    client_id: 6b1400c3-5187-49af-a87c-d2ab9bda657c
    secret: U8pm17n2VwbcTJk8FkeqDoILDHjPlyH7gorINdJgXjE=
    publisher: MicrosoftWindowsServer
    offer: WindowsServer
    sku: 2008-R2-SP1
  register: result
