---
- name: Deallocate VM
  azure_rm_virtualmachine:
    client_id: "{{ client_id }}"
    secret: "{{ secret }}"
    subscription_id: "{{ subscription_id }}"
    tenant: "{{ tenant }}"
    resource_group: "{{ resource_group }}"
    name: "{{ item }}"
    allocated: no
  with_items: "{{ vm_name }}"
  register: output
